version: 2.1

orbs:
  docker: circleci/docker@0.5.20
  slack: circleci/slack@3.4.2

jobs:
  build:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          image: bugfire/golang-test
      - slack/status:
          success_message: ':pen_good: $CIRCLE_BRANCH のビルドに成功しました'
          failure_message: ':pen_naki: $CIRCLE_BRANCH のビルドに失敗しました'
          webhook: '${SLACK_WEBHOOK}'
  deploy:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          image: bugfire/golang-test
      - run:
          command: |
            echo "Digest is $(</tmp/digest.txt)"

workflows:
  commit:
    jobs:
      - build:
          filters:
            branches:
             only: /.*/
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
